### ISSUE TITLE
Unable to find element with ID 2.

### ISSUE THREAD

**Issue by sugarshin** [sugarshin/sugarshin.net#19]
app-c7f439c….js:1 Uncaught Error: Minified React error #32; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=32&args[]=2 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

refs:

- https://facebook.github.io/react/docs/error-decoder.html?invariant=32&args[]=2
- https://github.com/zeit/next.js/issues/1068
- https://github.com/facebook/react/issues/7093

**Comment by abeMedia** [comment]
Did you eventually figure out this error?

**Comment by sugarshin** [comment]
I replaced by Nuxt.js
